package(
  default_visibility = ["//visibility:public"]
)

cc_library(
  name = "composable_func",
  hdrs = ["composable_func.h"],
)

cc_library(
  name = "identity",
  hdrs = ["identity.h"]
)
