package(
  default_visibility = ["//visibility:public"]
)

cc_library(
  name = "autodiff_double",
  hdrs = ["autodiff_double.h"],
  srcs = ["autodiff_double.cc"],
  deps = [
    "//src/dual:dual",
    "//src/dual:dual_func",
  ],
)
