cc_binary(
  name = "sandbox",
  srcs = ["sandbox.cc"],
  deps = [
    "//src/autodiff:autodiff",
    "//src/double:autodiff_double",
    "//src/tensor:tensor"
  ],
)

cc_binary(
  name = "single_var",
  srcs = ["single_var.cc"],
  deps = [
    "//src/autodiff:autodiff",
    "//src/double:autodiff_double",
  ],
)
