cc_binary(
  name = "single_var",
  srcs = ["single_var.cc"],
  deps = [
    "//src/autodiff:autodiff",
    "//src/double:autodiff_double",
  ],
)

cc_binary(
  name = "multi_var",
  srcs = ["multi_var.cc"],
  deps = [
    "//src/autodiff:autodiff",
    "//src/double:autodiff_double",
  ],
)

cc_binary(
  name = "smooth",
  srcs = ["smooth.cc"],
  deps = [
    "//src/smooth:smooth",
  ],
)
